# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(918, 782)
        MainWindow.setMaximumSize(QtCore.QSize(920, 782))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(900, 300))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/Images/covid-19-4855688_1920.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.img_lbl = QtWidgets.QLabel(self.centralwidget)
        self.img_lbl.setEnabled(True)
        self.img_lbl.setMaximumSize(QtCore.QSize(900, 300))
        self.img_lbl.setText("")
        self.img_lbl.setScaledContents(True)
        self.img_lbl.setObjectName("img_lbl")
        self.gridLayout.addWidget(self.img_lbl, 1, 0, 1, 1)
        self.show_btn = QtWidgets.QPushButton(self.centralwidget)
        self.show_btn.setObjectName("show_btn")
        self.gridLayout.addWidget(self.show_btn, 2, 0, 1, 1)
        self.gridLayout.setRowStretch(1, 1)
        self.gridLayout.setRowStretch(2, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.show_btn.setText(_translate("MainWindow", "Select X-ray image"))
import corona_app_rc
